receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  debug:
    verbosity: basic
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
